server:
  port: 8087
spring:
  application:
    name: auth-service
  rabbitmq:
    virtual-host: leyou
    username: admin
    password: admin
    host: 172.16.0.8
eureka:
  client:
    service-url:
      defaultZone: http://119.29.134.37:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true  #当你获取host时，返回的不是主机名，而是ip
    ip-address: 119.29.134.37
    lease-expiration-duration-in-seconds: 10 #10秒不发送九过期
    lease-renewal-interval-in-seconds: 5 #每隔5秒发一次心跳
leyou:
  jwt:
    secret: leyou@Login(Auth}*^31)&heiMa% # 登录校验的密钥
    pubKeyPath: /var/lib/docker/tmp/rsa/rsa.pub # 公钥地址
    priKeyPath: /var/lib/docker/tmp/rsa/rsa.pri # 私钥地址
    expire: 3000 # 过期时间,单位分钟
    cookieName: LY_TOKEN
    cookieMaxAge: 300

ribbon:
  ConnectTimeout: 4000 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms