server:
  port: 8092
  tomcat:
    max-connections: 5000
spring:
  application:
    name: comments-service
  data:
    mongodb:
      host: 172.16.0.8
      database: leyoudb
  datasource:
    url: jdbc:mysql://172.16.16.16:3306/leyou?characterEncoding=UTF-8&useSSL=false
    username: root
    password: xsj@2019
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  rabbitmq:
    virtual-host: leyou
    username: admin
    password: admin
    host: 172.16.0.8
  redis:
    host: 172.16.0.8
  jackson:
    default-property-inclusion: non_null # 配置json处理时忽略空值
eureka:
  client:
    service-url:
      defaultZone: http://119.29.134.37:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true  #当你获取host时，返回的不是主机名，而是ip
    ip-address: 119.29.134.37
    lease-expiration-duration-in-seconds: 10 #10秒不发送九过期
    lease-renewal-interval-in-seconds: 5 #每隔5秒发一次心跳
ribbon:
  ConnectTimeout: 4000 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数

leyou:
  worker:
    workerId: 2
    dataCenterId: 2
  jwt:
    cookieName: LY_TOKEN
    pubKeyPath: /test/rsa.pub # 公钥地址