server:
  port: 8082
spring:
  application:
    name: upload-service
  rabbitmq:
    virtual-host: leyou
    username: admin
    password: admin
    host: 172.16.0.8
  servlet:
    multipart:
      max-file-size: 10MB # 限制文件上传的大小
# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://119.29.134.37:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 119.29.134.37
    instance-id: ${spring.application.name}:${server.port}
fdfs:
  so-timeout: 1501 #超时时间
  connect-timeout: 601 #连接超时时间
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址
    - 129.204.127.41:22122